import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Header2 } from "../components/Header";
import { homePageData } from "../data/HomePage";
import { useEffect, useState } from "react";
export default function Home() {
  const [update, setUpdate] = useState(0);
  const [values, setValues] = useState([]);

  useEffect(() => {
    fetch("https://jsonplaceholder.typicode.com/photos")
      .then((response) => response.json())
      .then((json) => setValues(json));
  }, []);

  // console.log(values);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header2 title={"Hello World"} />
      <main className={styles.main}>
        {homePageData.flatMap((data, index) => (
          <div key={index}>
            <h2>{data.name}</h2>
            <p>{data.description}</p>
          </div>
        ))}
        {values.map((value, index) => (
          <div key={index}>
            <div>{value.id}</div>
            <div>{value.title}</div>
            {/* <img src={value.url} alt={value.title} /> */}
            <Image
              src={value.url}
              width={100}
              height={100}
              objectFit="contain"
            />
          </div>
        ))}
        <div>{update}</div>
        <button
          style={{ fontSize: "30px" }}
          className=""
          onClick={() => setUpdate(update + 1)}
        >
          Hello
        </button>
        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
